import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layouts/Layout";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import { cn } from "@/lib/utils";
import MainWrapper from "@/components/wrapper/main-wrapper";
import TopNav from "@/components/layouts/top-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.webp" type="image/webp" />
      </head>
      <body className={cn(inter.className)}>
        <TopNav />
        <MainWrapper>
          <Layout>{children}</Layout>
        </MainWrapper>
      </body>
    </html>
  );
}
